# Copyright 2021 The JAX Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 文件职责：实现 checkify 变换，把 `check` 断言与各类运行时错误检查（NaN、越界索引、
# 除零等）从 Python 异常效果改写为显式的函数式 `Error` 值，使带检查的函数仍可被
# jit/scan/while 等变换暂存。
# 核心是 `Error` pytree（用 `ErrorEffect` 记录每类错误是否触发、错误码与载荷）以及
# 一组按原语注册的 `error_checks` 规则，它们负责在解释 jaxpr 时累积错误状态。
# 本块还定义了 `check_p` 原语及其实现、批处理、JVP 与 MLIR 降级规则，以及
# `checkify` 变换的骨架。
from __future__ import annotations

from collections.abc import Callable, Sequence
import dataclasses
import functools
import itertools as it
from typing import TypeVar, Any

import numpy as np

from jax._src import ad_checkpoint
from jax._src import api
from jax._src import api_util
from jax._src import callback
from jax._src import config
from jax._src import core
from jax._src import custom_derivatives
from jax._src import dtypes
from jax._src import effects
from jax._src import lax
from jax._src import linear_util as lu
from jax._src import mesh as mesh_lib
from jax._src import numpy as jnp
from jax._src import pjit
from jax._src import shard_map as jshmap
from jax._src import sharding_impls
from jax._src import source_info_util
from jax._src import traceback_util
from jax._src import tree_util as jtu
from jax._src.ad_util import SymbolicZero
from jax._src.hijax import call_hi_primitive_p
from jax._src.interpreters import ad
from jax._src.interpreters import batching
from jax._src.interpreters import mlir
from jax._src.interpreters import partial_eval as pe
from jax._src.partition_spec import PartitionSpec as P
from jax._src.tree_util import tree_flatten
from jax._src import flattree as ft
from jax._src.tree_util import tree_map
from jax._src.tree_util import tree_unflatten
from jax._src.typing import Array
from jax._src.util import (split_list, safe_map, safe_zip, unzip3,
                           weakref_lru_cache, HashableWrapper, foreach)

# 向后兼容：一些下游用户隐式依赖这次导入，
# 会在没有显式导入的情况下引用 jax.experimental.shard_map。
# TODO(yashkatariya): 待用户迁移到 jax.shard_map 后移除这段。
try:
  import jax.experimental.shard_map as _  # pyrefly: ignore[missing-import]  # noqa: F401
except ImportError:
  pass

source_info_util.register_exclusion(__file__)
traceback_util.register_exclusion(__file__)

map, unsafe_map = safe_map, map
zip, unsafe_zip = safe_zip, zip

Bool = bool | Array
Int = int | Array
ErrorCategory = type['JaxException']
Payload = list[np.ndarray | Array]
PyTreeDef = jtu.PyTreeDef
Out = TypeVar('Out')

# 具体错误

class JaxException(Exception):
  """可以携带 JAX 运行时信息的错误消息的 Python 异常。"""

  def __init__(self, traceback_info):
    self.traceback_info = traceback_info
    # TODO(lenamartens): 当回溯不再泄漏追踪器时重新启用。
    # self.with_traceback(self.traceback_info)

  def __init_subclass__(cls):
    jtu.register_pytree_node_class(cls)

  def tree_flatten(self, /):
    return ([], self.traceback_info)

  @classmethod
  def tree_unflatten(cls, metadata, payload, /):
    del payload  # 未使用。
    return cls(metadata)

  def get_effect_type(self) -> ErrorEffect:
    raise NotImplementedError


@functools.total_ordering
@dataclasses.dataclass(eq=True, frozen=True, slots=True)
class ErrorEffect(effects.Effect):
  error_type: type[JaxException]
  shape_dtypes: tuple[api.ShapeDtypeStruct, ...]

  def __lt__(self, other: ErrorEffect):
    shape_dtypes = lambda x: tuple((sd.shape, str(sd.dtype))  # dtype 不可比较
                                   for sd in x.shape_dtypes)
    unpack = lambda x: (str(x.error_type), shape_dtypes(x))
    return (unpack(self) < unpack(other))

effects.lowerable_effects.add_type(ErrorEffect)
effects.control_flow_allowed_effects.add_type(ErrorEffect)
effects.custom_derivatives_allowed_effects.add_type(ErrorEffect)
effects.remat_allowed_effects.add_type(ErrorEffect)

class DivisionByZeroError(JaxException):

  def __str__(self):
    return 'division by zero'

  def get_effect_type(self):
    return ErrorEffect(DivisionByZeroError, ())

class NaNError(JaxException):

  def __init__(self, traceback_info, primitive_name):
    super().__init__(traceback_info)
    self.prim = primitive_name

  def tree_flatten(self):
    return ([], (self.traceback_info, self.prim))

  @classmethod
  def tree_unflatten(cls, metadata, payload):
    del payload
    return cls(*metadata)

  def get_effect_type(self):
    return ErrorEffect(NaNError, ())

  def __str__(self):
    return f'nan generated by primitive: {self.prim}.'

class OOBError(JaxException):

  def __init__(self, traceback_info, primitive_name, operand_shape, payload):
    super().__init__(traceback_info)
    self.prim = primitive_name
    self.operand_shape = operand_shape
    self._payload = payload

  def tree_flatten(self):
    return ([self._payload], (self.traceback_info, self.prim, self.operand_shape))

  @classmethod
  def tree_unflatten(cls, metadata, payload):
    return cls(*metadata, payload=payload[0])

  def __str__(self):
    return (f'out-of-bounds indexing for array of '
            f'shape {self.operand_shape}: '
            f'index {self._payload[0]} is out of bounds for axis '
            f'{self._payload[1]} with size {self._payload[2]}. ')

  def get_effect_type(self):
    return ErrorEffect(OOBError, (api.ShapeDtypeStruct((3,), np.int32),))

class FailedCheckError(JaxException):

  def __init__(self, traceback_info, fmt_string, *a, **k):
    super().__init__(traceback_info)
    self.fmt_string = fmt_string
    self.args = a
    self.kwargs = k

  def tree_flatten(self):
    return ((self.args, self.kwargs),  # 叶子
            (self.traceback_info, self.fmt_string))  # 树结构定义

  @classmethod
  def tree_unflatten(cls, metadata, payload):
    args, kwargs = payload
    return cls(*metadata, *args, **kwargs)

  def __str__(self):
    return (self.fmt_string.format(*self.args, **self.kwargs)
            + ' (`check` failed)')

  def get_effect_type(self):
    vals = jtu.tree_leaves((self.args, self.kwargs))
    return ErrorEffect(
        FailedCheckError,
        tuple(api.ShapeDtypeStruct.like(x) for x in vals))

@dataclasses.dataclass
class BatchedError(JaxException):
  error_mapping: dict[tuple[int, ...], JaxException]

  def __post_init__(self):
    traceback_info = list(self.error_mapping.values())[0].traceback_info
    super().__init__(traceback_info)


  def __str__(self):
    return '\n'.join(f'at mapped index {", ".join(map(str, idx))}: {e}'
                     for idx, e in self.error_mapping.items())


# 错误值

@jtu.register_pytree_node_class
@dataclasses.dataclass(frozen=True, slots=True)
class Error:
  _pred: dict[ErrorEffect, Bool]
  _code: dict[ErrorEffect, Int]
  _metadata: dict[Int, PyTreeDef]  # 从错误码到 JaxException 树结构定义的映射。
  _payload: dict[ErrorEffect, Payload]

  def get(self) -> str | None:
    """若发生错误则返回错误消息，未发生错误则返回 None。"""
    exp = self.get_exception()
    if exp is not None:
      return str(exp)
    return None

  def get_exception(self) -> JaxException | None:
    """若发生错误则返回 Python 异常，未发生错误则返回 None。"""
    if any(np.shape(v) for v in self._pred.values()):
      return self._get_batched_exception()
    else:
      min_code: Int | None = None
      cur_effect: ErrorEffect | None = None
      for error_effect, code in self._code.items():
        if self._pred[error_effect]:
          if min_code is None or code < min_code:
            min_code = code
            cur_effect = error_effect

      if cur_effect is not None:
        assert min_code is not None
        return tree_unflatten(self._metadata[int(min_code)],
                              self._payload[cur_effect])
    return None

  def throw(self):
    _check_error(self)

  def __str__(self):
    return f'Error({self.get()})'

  # 内部辅助函数

  def _get_batched_exception(self) -> BatchedError | None:
    shape = np.shape(list(self._pred.values())[0])
    error_mapping = {}
    for idx in np.ndindex(*shape):
      min_code: Int | None = None
      cur_effect: ErrorEffect | None = None
      for error_effect, code in self._code.items():
        if self._pred[error_effect][idx]:  # pyrefly: ignore[bad-index]
          if min_code is None or code[idx] < min_code:  # pyrefly: ignore[bad-index]
            min_code = code[idx]  # pyrefly: ignore[bad-index]
            cur_effect = error_effect

      if cur_effect is not None:
        assert min_code is not None
        payload = tree_map(lambda x, i=idx: x[i], self._payload[cur_effect])
        jax_error = tree_unflatten(self._metadata[int(min_code)], payload)
        error_mapping[idx] = jax_error
    if error_mapping:
      return BatchedError(error_mapping)
    else:
      return None

  def _update(self, effect_type: ErrorEffect, pred, code, metadata, payload):
    new_errs = {**self._pred, **{effect_type: pred}}
    new_codes = {**self._code, **{effect_type: code}}
    new_payload = {**self._payload, **{effect_type: payload}}
    new_metadata = {**self._metadata, **metadata}
    return Error(new_errs, new_codes, new_metadata, new_payload)

  def _add_placeholder_effects(self, effects: set[ErrorEffect]):
    """用 `effects` 及其载荷的 np.ones 数组把 Error 填充完整。"""
    new_err = self._pred.copy()
    new_code = self._code.copy()
    new_payload = self._payload.copy()
    for effect in effects:
      if effect not in self._pred.keys():
        new_err[effect] = False
        new_payload[effect] = list(
            tree_map(lambda a: jnp.ones(a.shape, a.dtype), effect.shape_dtypes))
        # 与该效果关联的错误值永远不会变为 True，
        # 因此无需设置有意义的错误码。
        new_code[effect] = -1
    return Error(new_err, new_code, self._metadata, new_payload)

  def _replace(self, *args, **kwargs):
    return dataclasses.replace(self, *args, **kwargs)

  # PyTree 方法

  def tree_flatten(self):
    return ((self._pred, self._code, self._payload), (self._metadata))

  @classmethod
  def tree_unflatten(cls, metadata, data):
    pred, code, payload = data
    return cls(pred, code, metadata, payload)

init_error = Error({}, {}, {}, {})  # 用作初始（空）错误的值。
next_code = it.count(1).__next__  # 全局唯一 id，也可以用 uuid4

def assert_func(error: Error, pred: Bool, new_error: JaxException) -> Error:
  code = next_code()
  effect_type = new_error.get_effect_type()
  new_payload, new_metadata = tree_flatten(new_error)
  return update_error(error, pred, code, {code: new_metadata}, new_payload, effect_type)

def update_error(error, pred, code, metadata, payload, effect_type):
  err_of_type = error._pred.get(effect_type, False)
  out_err = err_of_type | pred
  out_code = lax.select(err_of_type, error._code.get(effect_type, -1), code)
  cur_payload = error._payload.get(effect_type, None)
  if cur_payload is not None:
    out_payload = tree_map(functools.partial(lax.select, err_of_type), cur_payload, payload)
  else:
    out_payload = payload
  return error._update(effect_type, out_err, out_code, metadata, out_payload)


## 用于传递函数式错误值的 Checkify 变换。

@lu.transformation_with_aux2
def _flatten_and_get_error_metadata_thunk(f, store, *invals):
  error, out = f(*invals)
  out_vals, out_tree = jtu.tree_flatten((error, out))
  store.store((out_tree, set(error._pred.keys())))
  return out_vals

def default_checkify_rule(primitive: core.Primitive, error: Error,
                          enabled_errors, *invals: core.Value,
                          **params: Any) -> tuple[Error, Sequence[core.Value]]:
  """`checkify` 解释器中原语的默认规则。"""
  if 'call_jaxpr' not in params:
    # 默认的非高阶原语情形：只调用原语，不更新错误。
    return error, primitive.bind(*invals, **params)

  # 下面的代码通过递归调用
  # checkify_jaxpr 来处理 call 与 map 类原语。
  err_vals, err_tree = jtu.tree_flatten(error)
  num_error_vals = len(err_vals)
  if 'donated_invars' in params:
    params = dict(params, donated_invars=(*[False]*num_error_vals,
                                          *params['donated_invars']))

  # call_jaxpr 处理
  call_jaxpr = params.pop('call_jaxpr')
  if isinstance(call_jaxpr, core.Jaxpr):  # 带附加常量的 jaxpr
    jaxpr, consts = call_jaxpr, call_jaxpr.consts
  else:
    jaxpr, consts = call_jaxpr, ()
  consts_ = tuple(HashableWrapper(c) for c in consts)
  partial_checkify = lu.hashable_partial(
      lu.wrap_init(checkify_jaxpr_flat_hashable, debug_info=jaxpr.debug_info),
      jaxpr, consts_, enabled_errors, err_tree)
  partial_checkify, metadata = _flatten_and_get_error_metadata_thunk(
      partial_checkify)

  all_vals = primitive.bind(*err_vals, *invals, subfuns=(partial_checkify,),
                            **params)

  out_tree, _ = metadata()
  error, out_vals = tree_unflatten(out_tree, all_vals)
  return error, out_vals

def checkify_jaxpr(jaxpr: core.Jaxpr, enabled_errors,
                   error: Error, *args) -> tuple[Error, list[core.Value]]:
  err_vals, err_tree = jtu.tree_flatten(error)
  return checkify_jaxpr_flat(jaxpr, jaxpr.consts,
                             enabled_errors, err_tree, *err_vals, *args)

def checkify_jaxpr_flat(jaxpr: core.Jaxpr, consts: Sequence[core.Value],
                        enabled_errors, err_tree: PyTreeDef,
                        *args: core.Value) -> tuple[Error, list[Any]]:
  env: dict[core.Var, Any] = {}
  err_vals, in_args = split_list(args, [err_tree.num_leaves])
  error = jtu.tree_unflatten(err_tree, err_vals)

  last_used = core.last_used(jaxpr)

  def read_env(var: core.Atom):
    if isinstance(var, core.Literal):
      return var.val
    return env[var]

  def write_env(var: core.Var, val: Any):
    env[var] = val

  foreach(write_env, jaxpr.constvars, consts)
  foreach(write_env, jaxpr.invars, in_args)

  # 解释器主循环
  for eqn in jaxpr.eqns:
    invals = map(read_env, eqn.invars)
    checkify_rule = error_checks.get(
        eqn.primitive, functools.partial(default_checkify_rule, eqn.primitive))
    name_stack = source_info_util.current_name_stack() + eqn.source_info.name_stack
    with (source_info_util.user_context(eqn.source_info.traceback,
                                        name_stack=name_stack),
          eqn.ctx.manager):
      error, outvals = checkify_rule(error, enabled_errors,
                                     *invals, **eqn.params)
    if eqn.primitive.multiple_results:
      foreach(write_env, eqn.outvars, outvals)
    else:
      write_env(eqn.outvars[0], outvals)
    core.clean_up_dead_vars(eqn, env, last_used)

  return error, map(read_env, jaxpr.outvars)

def checkify_jaxpr_flat_hashable(jaxpr, hashable_consts, enabled_errors,
                                 err_tree, *args):
  consts = tuple(c.x for c in hashable_consts)
  return checkify_jaxpr_flat(jaxpr, consts, enabled_errors, err_tree, *args)

@lu.transformation_with_aux2
def flatten_fun_output(f, store, *args):
  ans = f(*args)
  ans, out_tree = tree_flatten(ans)
  store.store(out_tree)
  return ans


def _reduce_any_error(error: Error):
  out_error = init_error
  for error_effect in error._pred.keys():
    errs, codes, payloads = (error._pred[error_effect],
                             error._code[error_effect],
                             error._payload[error_effect])
    reduced_idx = jnp.argsort(errs)[-1]
    pred, code, payload = tree_map(lambda x, idx=reduced_idx: x[idx],
                                   (errs, codes, payloads))
    out_error = out_error._update(error_effect, pred, code, {}, payload)

  out_error = out_error._replace(_metadata=error._metadata)
  return out_error

## check_p 原语

check_p = core.Primitive('check')
check_p.is_effectful = lambda _: True
check_p.multiple_results = True  # 零个结果


def _pp_check(eqn, context, settings) -> core.pp.Doc:
  annotation = (source_info_util.summarize(eqn.source_info)
                if settings.source_info else None)
  name_stack_annotation = (f'[{eqn.source_info.name_stack}]'
                           if settings.name_stack else None)
  trimmed_params = sorted((k, v) for (k, v) in eqn.params.items()
                          if k != "err_tree")
  rhs = [core.pp.text(eqn.primitive.name, annotation=name_stack_annotation),
         core.pp_kv_pairs(trimmed_params, context, settings),
         core.pp.text(" ") + core.pp_vars(eqn.invars, context)]
  return core.pp.concat([core.pp.text("", annotation), *rhs])

core.pp_eqn_rules[check_p] = _pp_check

# TODO(lenamartens): 改为继承 Exception 而不是 ValueError。
class JaxRuntimeError(ValueError):
  pass

@check_p.def_impl
def check_impl(*args, err_tree, debug):
  if debug:
    # 空操作（check 只有在被释放时才会触发）
    return []
  error = tree_unflatten(err_tree, args)
  exc = error.get_exception()
  if exc:
    filtered_tb = traceback_util.filter_traceback(
        exc.traceback_info.as_python_traceback())
    exc.with_traceback(filtered_tb)
    raise JaxRuntimeError(str(exc)) from exc
  return []

@check_p.def_effectful_abstract_eval
def check_abstract_eval(*args, err_tree, debug):
  del debug
  return [], set(tree_unflatten(err_tree, args)._pred.keys())

# TODO(lenamartens) 补充深入的错误解释，并在模块文档中链接。
functionalization_error = ValueError(
    'Cannot abstractly evaluate a checkify.check which was not'
    ' functionalized. This probably means you tried to stage'
    ' (jit/scan/pmap/...) a `check` without functionalizing it'
    ' through `checkify.checkify`.'
    )

def check_lowering_rule(ctx, *args, err_tree, debug):
  if debug:
    # 空操作（check 只有在被释放时才会触发）
    return []
  if not config.xla_runtime_errors.value:
    raise functionalization_error

  out_op, _, _ = callback.emit_python_callback(
      ctx, callback=functools.partial(python_err, err_tree),
      token=None,
      operands=args,
      operand_avals=list(ctx.avals_in),
      result_avals=list(ctx.avals_out),
      has_side_effect=True,
      returns_token=False)
  return out_op

def check_lowering_rule_unsupported(*a, debug, **k):
  if debug:
    return []
  raise functionalization_error

def python_err(err_tree, *args):
  error = tree_unflatten(err_tree, args)
  _check_error(error)
  return []

mlir.register_lowering(check_p, check_lowering_rule_unsupported,
                       platform='tpu')
mlir.register_lowering(check_p, check_lowering_rule,
                       platform='cpu')
mlir.register_lowering(check_p, check_lowering_rule,
                       platform='gpu')

def check_batching_rule(batched_args, batch_dims, *, err_tree, debug):
  size = next(x.shape[dim] for x, dim in zip(batched_args, batch_dims)
              if dim is not None)
  batched_args = (batching.bdim_at_front(a, d, size)
                  for a, d in zip(batched_args, batch_dims))
  err = tree_unflatten(err_tree, batched_args)
  _check_error(err, debug=debug)
  return [], []
batching.primitive_batchers[check_p] = check_batching_rule

def check_jvp_rule(primals, _, *, err_tree, debug):
  # 检查原始值，丢弃切向量。
  check_p.bind(*primals, err_tree=err_tree, debug=debug)
  return [], []
ad.primitive_jvps[check_p] = check_jvp_rule

## checkify 规则

ErrorCheckRule = Callable  # (Error, FrozenSet[ErrorCategory], *in_vals, **params) -> (Any, Error)
error_checks: dict[core.Primitive, ErrorCheckRule] = {}


def get_traceback():
  return source_info_util.current().traceback

def nan_error_check(prim, error, enabled_errors, *in_vals, **params):
  out = prim.bind(*in_vals, **params)
  err = check_nans(prim, error, enabled_errors, out)
  return err, out

def check_nans(prim, error, enabled_errors, out):
  if NaNError not in enabled_errors:
    return error

  def isnan(x):
    if dtypes.issubdtype(x.dtype, dtypes.prng_key):
      return False
    return jnp.any(jnp.isnan(x))

  any_nans = (jnp.any(jnp.array([isnan(x) for x in out]))
              if prim.multiple_results else isnan(out))
  return assert_func(error, any_nans, NaNError(get_traceback(), prim.name))


# 所有可能产生 NaN 的原语。
nan_primitives = [lax.acos_p, lax.acosh_p, lax.add_p, lax.asin_p, lax.asinh_p,
                  lax.atan2_p, lax.atan_p, lax.atanh_p, lax.bessel_i0e_p,
                  lax.bessel_i1e_p, lax.cbrt_p, lax.conv_general_dilated_p,
                  lax.cos_p, lax.cosh_p, lax.cumlogsumexp_p, lax.cummax_p,
                  lax.cummin_p, lax.cumprod_p, lax.cumsum_p, lax.digamma_p,
                  lax.dot_general_p, lax.erf_inv_p, lax.erf_p, lax.erfc_p,
                  lax.exp_p, lax.expm1_p, lax.fft_p, lax.igamma_grad_a_p,
                  lax.igamma_p, lax.igammac_p, lax.integer_pow_p, lax.lgamma_p,
                  lax.linear_solve_p, lax.log1p_p, lax.log_p, lax.logistic_p,
                  lax.mul_p, lax.pad_p, lax.pow_p, lax.psum_p,
                  lax.reduce_p, lax.reduce_prod_p,
                  lax.reduce_sum_p, lax.reduce_window_p,
                  lax.reduce_window_sum_p, lax.regularized_incomplete_beta_p,
                  lax.rem_p, lax.rng_uniform_p, lax.rsqrt_p, lax.sin_p,
                  lax.sinh_p, lax.sqrt_p, lax.sub_p, lax.tan_p, lax.tanh_p]

for _prim in nan_primitives:
  error_checks[_prim] = functools.partial(nan_error_check, _prim)


def dynamic_slice_error_check(error, enabled_errors, operand, *start_indices, slice_sizes):
  out = lax.dynamic_slice_p.bind(operand, *start_indices, slice_sizes=slice_sizes)

  if OOBError not in enabled_errors:
    return error, out

  start_indices = jnp.array(start_indices)
  operand_dims = np.array(operand.shape, dtype=start_indices.dtype)
  slice_sizes = np.array(slice_sizes, dtype=start_indices.dtype)
  oob_mask = (start_indices < 0) | (start_indices + slice_sizes > operand_dims)

  payload = oob_payload(oob_mask, start_indices, range(operand.ndim), operand.shape)
  error = assert_func(error, jnp.any(oob_mask), OOBError(get_traceback(), "dynamic_slice", operand.shape, payload))
  return error, out
error_checks[lax.dynamic_slice_p] = dynamic_slice_error_check

def dynamic_update_slice_error_check(error, enabled_errors, operand, update, *start_indices):
  out = lax.dynamic_update_slice_p.bind(operand, update, *start_indices)

  if OOBError not in enabled_errors:
    return error, out

  operand_dims = np.array(operand.shape)
  update_dims = np.array(update.shape)
  start_indices = jnp.array(start_indices)
  oob_mask = (start_indices < 0) | (start_indices + update_dims > operand_dims)

  payload = oob_payload(oob_mask, start_indices, range(operand.ndim), operand.shape)
  error = assert_func(error, jnp.any(oob_mask), OOBError(get_traceback(), "dynamic_update_slice", operand.shape, payload))
  return error, out
error_checks[lax.dynamic_update_slice_p] = dynamic_update_slice_error_check

def gather_error_check(error, enabled_errors, operand, start_indices, *,
                       dimension_numbers, slice_sizes, unique_indices,
                       indices_are_sorted, mode, fill_value):
  out = lax.gather_p.bind(
      operand, start_indices, dimension_numbers=dimension_numbers,
      slice_sizes=slice_sizes, unique_indices=unique_indices,
      indices_are_sorted=indices_are_sorted, mode=mode, fill_value=fill_value)

  if OOBError not in enabled_errors:
    return error, out

  # 对比 lax._gather_translation_rule 中的越界掩码逻辑
  dnums = dimension_numbers
  operand_dims = np.array(operand.shape)
  num_batch_dims = len(start_indices.shape) - 1

  upper_bound = operand_dims[np.array(dnums.start_index_map)]
  upper_bound -= np.array(slice_sizes)[np.array(dnums.start_index_map)]
  upper_bound = jnp.expand_dims(upper_bound, axis=tuple(range(num_batch_dims)))
  oob_mask = (start_indices < 0) | (start_indices > upper_bound.astype(start_indices.dtype))

  payload = oob_payload(oob_mask, start_indices, dnums.start_index_map, operand.shape)
  error = assert_func(error, jnp.any(oob_mask), OOBError(get_traceback(), "gather", operand.shape, payload))
  return error, out
error_checks[lax.gather_p] = gather_error_check

def div_error_check(error, enabled_errors, x, y):
  """检查除零与 NaN。"""
  if DivisionByZeroError in enabled_errors:
    any_zero = jnp.any(jnp.equal(y, 0))
    error = assert_func(error, any_zero, DivisionByZeroError(get_traceback()))
  return nan_error_check(lax.div_p, error, enabled_errors, x, y)
error_checks[lax.div_p] = div_error_check

def eval_jaxpr_error_check(error, enabled_errors, *invals, call_jaxpr, **_):
  return checkify_jaxpr(call_jaxpr, enabled_errors, error, *invals)
error_checks[pe.eval_jaxpr_p] = eval_jaxpr_error_check

def oob_payload(oob_mask, indices, dims_map, operand_shape):
  # 取出第一个越界索引、轴与轴长度，以便加入错误消息。
  flat_idx = jnp.argmin(jnp.logical_not(oob_mask))
  multi_idx = jnp.unravel_index(flat_idx, indices.shape)
  oob_axis = jnp.array(dims_map)[multi_idx[-1]]
  oob_axis_size = jnp.array(operand_shape)[oob_axis]
  oob_index = jnp.ravel(indices)[flat_idx]
  payload = jnp.array([oob_index, oob_axis, oob_axis_size], dtype=np.int32)
  return payload

def scatter_oob(operand, indices, updates, dnums):
  # 参考：见 scatter_translation_rule 中使用的截断逻辑
  slice_sizes = []
  pos = 0
  for i in range(len(operand.shape)):
    if i in dnums.inserted_window_dims:
      slice_sizes.append(1)
    else:
      slice_sizes.append(updates.shape[dnums.update_window_dims[pos]])
      pos += 1

  upper_bound = np.array([operand.shape[i] - slice_sizes[i]
                          for i in dnums.scatter_dims_to_operand_dims],
                         np.int64)
  upper_bound = np.minimum(upper_bound, np.iinfo(indices.dtype).max)
  upper_bound = lax.broadcast_in_dim(upper_bound, indices.shape,
                                     (len(indices.shape) - 1,))

  lower_oob = jnp.less(indices, 0)
  upper_oob = jnp.greater(indices, upper_bound.astype(indices.dtype))
  oob_mask = jnp.logical_or(lower_oob, upper_oob)
  payload = oob_payload(oob_mask, indices,
                        dnums.scatter_dims_to_operand_dims, operand.shape)
  return jnp.any(oob_mask), payload
def scatter_error_check(prim, error, enabled_errors, operand, indices, updates,
                        *, update_jaxpr, update_consts, dimension_numbers,
                        indices_are_sorted, unique_indices, mode):
  """检查索引是否越界，以及更新是否产生 NaN。"""
  out = prim.bind(
      operand, indices, updates, update_jaxpr=update_jaxpr,
      update_consts=update_consts, dimension_numbers=dimension_numbers,
      indices_are_sorted=indices_are_sorted, unique_indices=unique_indices,
      mode=mode)

  if OOBError not in enabled_errors:
    return error, out

  out_of_bounds, payload = scatter_oob(operand, indices, updates, dimension_numbers)
  oob_error = OOBError(get_traceback(), prim.name, operand.shape, payload)
  error = assert_func(error, out_of_bounds, oob_error)
  error = check_nans(prim, error, enabled_errors, out)
  return error, out
error_checks[lax.scatter_p] = functools.partial(scatter_error_check, lax.scatter_p)
error_checks[lax.scatter_add_p] = functools.partial(scatter_error_check,
                                                    lax.scatter_add_p)
error_checks[lax.scatter_mul_p] = functools.partial(scatter_error_check,
                                                    lax.scatter_mul_p)
error_checks[lax.scatter_min_p] = functools.partial(scatter_error_check,
                                                    lax.scatter_min_p)
error_checks[lax.scatter_max_p] = functools.partial(scatter_error_check,
                                                    lax.scatter_max_p)

# 高阶原语的错误检查规则

@jtu.register_static
class ErrorEffects:
  def __init__(self, val):
    self.val = val

@weakref_lru_cache
def jaxpr_to_checkify_jaxpr(
    jaxpr: core.Jaxpr, enabled_errors, err_tree: PyTreeDef,
    *flat_err_and_in_vals) -> tuple[core.Jaxpr, PyTreeDef, set[ErrorEffect]]:

  def fun_wrapped(*invals):
    error, out = checkify_jaxpr_flat(
        jaxpr, jaxpr.consts, enabled_errors, err_tree, *invals)
    error_effects = ErrorEffects(set(error._pred.keys()))
    return (error, out), error_effects

  debug_info = jaxpr.debug_info.with_unknown_names()
  args_avals = ft.flatten((flat_err_and_in_vals, {}))
  checked_jaxpr, full_out_avals = pe.trace_to_jaxpr(fun_wrapped, args_avals, debug_info)
  out_avals, error_effects = full_out_avals.unpack()
  error_effects = error_effects.unflatten().val
  return checked_jaxpr, out_avals.tree, error_effects

def cond_error_check(error: Error, enabled_errors, index, *ops,
                     branches, **params):
  # 从所有分支中取出错误效果，这样调用 cond 时就能传入
  # 一个合并了这些效果的错误。
  err_vals, err_tree = jtu.tree_flatten(error)
  in_avals = map(core.typeof, [*err_vals, *ops])
  def get_error_effects_from_jaxpr(jxpr):
    _, _, effects = jaxpr_to_checkify_jaxpr(jxpr, enabled_errors, err_tree,
                                            *in_avals)
    return effects
  effects = [get_error_effects_from_jaxpr(jxpr) for jxpr in branches]
  merged_error = error._add_placeholder_effects(set().union(*effects))
  err_vals, err_tree = jtu.tree_flatten(merged_error)

  # 把各分支的 jaxpr 更新为已 checkify 的 jaxpr。
  in_avals = map(core.typeof, [*err_vals, *ops])
  new_branches, out_trees, _ = unzip3(
      jaxpr_to_checkify_jaxpr(
          jxpr, enabled_errors, err_tree, *in_avals) for jxpr in branches)

  err_and_outs = lax.cond_p.bind(
      index, *err_vals, *ops,
      branches=tuple(new_branches), **params)

  # 我们需要跨 out_trees（一个元组）合并元数据
  err0, out = tree_unflatten(out_trees[0], err_and_outs)
  merged_metadata = err0._metadata
  for tr in out_trees[1:]:
    err, _ = tree_unflatten(tr, err_and_outs)
    merged_metadata = {**merged_metadata, **err._metadata}
  return err0._replace(_metadata=merged_metadata), out
error_checks[lax.cond_p] = cond_error_check

def scan_error_check(error, enabled_errors, *in_flat, reverse, length, jaxpr,
                     ft_in, ft_out, unroll):

  consts, carry, xs = map(list, ft_in.update(in_flat).unpack())
  xs_mapped = [core.mapped_aval(length, 0, core.typeof(val)) for val in xs]
  # 查询循环体的效果，构造一个包含所有效果的合并错误
  # （使得传入与传出的被携带错误具有相同类型）。
  err_vals, err_tree = jtu.tree_flatten(error)
  new_in_aval = map(core.typeof, [*err_vals, *consts, *carry]) + xs_mapped
  _, _, effects = jaxpr_to_checkify_jaxpr(jaxpr, enabled_errors,
                                          err_tree, *new_in_aval)

  merged_error = error._add_placeholder_effects(effects)
  err_vals, err_tree = jtu.tree_flatten(merged_error)

  # 创建已检查的 jaxpr，并对输入做所需的预处理。
  new_in_aval = map(core.typeof, [*err_vals, *consts, *carry]) + xs_mapped
  checked_jaxpr_, out_tree, _ = jaxpr_to_checkify_jaxpr(jaxpr, enabled_errors,
                                                        err_tree, *new_in_aval)

  tomove = ([False] * len(err_vals) + [True] * len(consts)
            + [False] * (len(carry) + len(xs)))
  checked_jaxpr = pe.move_binders_to_front(checked_jaxpr_, tomove)
  new_in_flat = [*consts, *err_vals, *carry, *xs]
  errs_g = ft.nones(len(err_vals))
  consts_g, carry_g, xs_g = ft_in.unpack()
  err_and_out = lax.scan_p.bind(
      *new_in_flat, reverse=reverse, length=length, jaxpr=checked_jaxpr,
      ft_in=ft.pack((consts_g, (errs_g, carry_g), xs_g)),
      ft_out=ft.pack(((errs_g, carry_g), ft_out.unpack()[1])), unroll=unroll)
  err, out = tree_unflatten(out_tree, err_and_out)
  return err, out

error_checks[lax.scan_p] = scan_error_check

def checkify_while_body_jaxpr(
    cond_jaxpr: core.Jaxpr, body_jaxpr: core.Jaxpr,
    enabled_errors, error: Error,
    c_consts_num: int) -> tuple[core.Jaxpr, PyTreeDef, set[ErrorEffect]]:
  cond_f = core.jaxpr_as_fun(cond_jaxpr)
  body_f = core.jaxpr_as_fun(body_jaxpr)
  def new_body_f(*c_consts_and_vals):
    c_consts, vals = split_list(c_consts_and_vals, [c_consts_num])
    out = body_f(*vals)
    # 这里检查下一次 cond 求值是否会出错
    lax.dce_sink(cond_f(*c_consts, *out))
    return out
  c_consts_avals = cond_jaxpr.in_avals[:c_consts_num]

  jaxpr, _ = pe.trace_to_jaxpr(
      new_body_f,
      ft.flatten(((*c_consts_avals, *body_jaxpr.in_avals), {})),
      debug_info=body_jaxpr.debug_info.with_unknown_names())
  err_vals, err_tree = jtu.tree_flatten(error)
  err_vals = map(core.typeof, err_vals)
  flat_err_and_in_vals = [*err_vals, *c_consts_avals, *body_jaxpr.in_avals]
  jaxpr, out_tree, error_effects = jaxpr_to_checkify_jaxpr(
      jaxpr, enabled_errors, err_tree, *flat_err_and_in_vals)
  return jaxpr, out_tree, error_effects


@weakref_lru_cache
def ignore_error_output_jaxpr(jaxpr, num_error_vals: int):
  """构造一个不输出其错误值的已检查 jaxpr。"""
  return jaxpr.replace(outvars=jaxpr.outvars[num_error_vals:])

def while_loop_error_check(error, enabled_errors, *in_flat, cond_nconsts,
                           cond_jaxpr, body_nconsts, body_jaxpr):
  if cond_jaxpr.out_avals[0].shape:
    # TODO(lenamartens, sharadmv): 支持批量化的 while。
    raise ValueError('Checkify does not support batched while-loops '
                     '(checkify-of-vmap-of-while). \nHint: if possible, move '
                     'the vmap to the outer level to get '
                     'vmap-of-checkify-of-while.')

  c_consts, b_consts, carry = split_list(in_flat, [cond_nconsts, body_nconsts])
  # 检查第一次 cond 求值是否会出错。
  error, _ = checkify_jaxpr(cond_jaxpr, enabled_errors, error, *c_consts, *carry)

  _, _, error_effects = checkify_while_body_jaxpr(cond_jaxpr, body_jaxpr,
                                                  enabled_errors, error,
                                                  cond_nconsts)
  # 合并后的错误！
  error = error._add_placeholder_effects(error_effects)
  err_vals, err_tree = jtu.tree_flatten(error)
  checked_body_jaxpr_, body_out_tree, _ = checkify_while_body_jaxpr(
      cond_jaxpr, body_jaxpr, enabled_errors, error, cond_nconsts)
  num_error_vals = len(err_vals)
  to_move = ([False] * num_error_vals + [True] * cond_nconsts
             + [True] * body_nconsts + [False] * len(carry))
  checked_body_jaxpr = pe.move_binders_to_front(checked_body_jaxpr_, to_move)

  cond_in_flat = [*err_vals, *c_consts, *carry]
  cond_in_flat = map(core.typeof, cond_in_flat)
  checked_cond_jaxpr, _, _ = jaxpr_to_checkify_jaxpr(cond_jaxpr, enabled_errors,
                                                     err_tree, *cond_in_flat)
  compat_cond_jaxpr_ = ignore_error_output_jaxpr(checked_cond_jaxpr, num_error_vals)
  to_move = [False] * num_error_vals + [True] * cond_nconsts + [False] * len(carry)
  compat_cond_jaxpr = pe.move_binders_to_front(compat_cond_jaxpr_, to_move)

  new_in_flat = [*c_consts, *c_consts, *b_consts, *err_vals, *carry]
  all_out_vals = lax.while_p.bind(
      *new_in_flat, cond_nconsts=cond_nconsts, cond_jaxpr=compat_cond_jaxpr,
      body_nconsts=cond_nconsts+body_nconsts, body_jaxpr=checked_body_jaxpr)
  # body_out_tree 会带有 cond 的全部元数据，因为它执行了一次 cond！
  error, out = tree_unflatten(body_out_tree, all_out_vals)
  return error, out
error_checks[lax.while_p] = while_loop_error_check

def pjit_error_check(error, enabled_errors, *vals_in, jaxpr,
                     in_shardings, out_shardings,
                     in_layouts, out_layouts,
                     donated_invars, ctx_mesh, name, inline, keep_unused,
                     compiler_options_kvs):
  # 把 jaxpr 转换为已检查的 jaxpr
  err_vals, err_tree = jtu.tree_flatten(error)
  new_vals_in = [*err_vals, *vals_in]
  in_avals = tuple(map(core.typeof, new_vals_in))
  checked_jaxpr, out_tree, _ = jaxpr_to_checkify_jaxpr(jaxpr, enabled_errors,
                                                       err_tree, *in_avals)

  # 更新 pjit 参数以考虑额外的错误值。
  num_error_vals = len(err_vals)
  num_out_error_vals = out_tree.num_leaves - len(out_shardings)
  sharding = sharding_impls.UNSPECIFIED
  new_in_shardings = (*[sharding] * num_error_vals, *in_shardings)
  new_in_layouts = (*[None] * num_error_vals, *in_layouts)
  new_donated_invars = (*[False] * num_error_vals, *donated_invars)

  new_out_shardings = (*[sharding] * num_out_error_vals, *out_shardings)
  new_out_layouts = (*[None] * num_out_error_vals, *out_layouts)

  err_and_out = pjit.jit_p.bind(
      *new_vals_in,
      jaxpr=checked_jaxpr,
      in_shardings=new_in_shardings,
      out_shardings=new_out_shardings,
      in_layouts=new_in_layouts,
      out_layouts=new_out_layouts,
      donated_invars=new_donated_invars,
      ctx_mesh=ctx_mesh,
      name=name,
      inline=inline,
      keep_unused=keep_unused,
      compiler_options_kvs=compiler_options_kvs,
  )
  return tree_unflatten(out_tree, err_and_out)
error_checks[pjit.jit_p] = pjit_error_check


def remat_error_check(error, enabled_errors, *vals_in, jaxpr, **params):
  err_vals, err_tree = jtu.tree_flatten(error)
  new_vals_in = [*err_vals, *vals_in]
  in_avals = tuple(map(core.typeof, new_vals_in))
  checked_jaxpr_, out_tree, _ = jaxpr_to_checkify_jaxpr(
      jaxpr, enabled_errors, err_tree, *in_avals)
  checked_jaxpr, () = checked_jaxpr_, checked_jaxpr_.consts
  err_and_out = ad_checkpoint.remat_p.bind(*new_vals_in, jaxpr=checked_jaxpr,
                                           **params)
  return tree_unflatten(out_tree, err_and_out)
error_checks[ad_checkpoint.remat_p] = remat_error_check


def call_hi_primitive_error_check(error, enabled_errors, *vals_in, _prim):
  if not isinstance(_prim, ad_checkpoint.RematTraced):
    return default_checkify_rule(call_hi_primitive_p, error, enabled_errors,
                                 *vals_in, _prim=_prim)
  err_vals, err_tree = jtu.tree_flatten(error)
  new_vals_in = [*err_vals, *vals_in]
  in_avals = tuple(map(core.typeof, new_vals_in))
  checked_jaxpr_, out_tree, _ = jaxpr_to_checkify_jaxpr(
      _prim.jaxpr, enabled_errors, err_tree, *in_avals)
  checked_jaxpr, consts = pe.separate_consts(checked_jaxpr_)
  new_prim = ad_checkpoint.RematTraced(checked_jaxpr, _prim.policy)
  err_and_out = new_prim(*consts, *new_vals_in)
  return tree_unflatten(out_tree, err_and_out)
error_checks[call_hi_primitive_p] = call_hi_primitive_error_check


def shard_map_error_check(
    error: Error, enabled_errors, *vals_in,
    jaxpr: core.Jaxpr, in_specs, out_specs, **kwargs
):
  if (mesh := kwargs.get('mesh')) is None:
    raise ValueError('Mesh must be provided for shard_map with checkify.')

  err_vals, err_tree = jtu.tree_flatten(error)
  num_error_vals = len(err_vals)
  # 输入错误的副本式分片。
  new_in_specs = (*([P()] * num_error_vals), *in_specs)
  new_vals_in = [*err_vals, *vals_in]
  in_avals = list(map(core.typeof, new_vals_in))
  manual_axes = kwargs.get('newly_manual_axes')
  check_vma = kwargs.get('check_vma')
  for i, v in enumerate(in_avals):
    if not (sharder := core.shard_aval_handlers.get(type(v))):
      raise ValueError(f'Unsupported aval type: {type(v)}')
    in_avals[i] = sharder(mesh, manual_axes, check_vma, new_in_specs[i], v)

  with (jshmap._extend_axis_env(mesh, manual_axes),
        mesh_lib.use_abstract_mesh(jshmap._as_manual_mesh(mesh, manual_axes)),
        config._check_vma(check_vma)):
    # 把 jaxpr 转换为已检查的 jaxpr
    checked_jaxpr, out_tree, _ = jaxpr_to_checkify_jaxpr(
        jaxpr, enabled_errors, err_tree, *in_avals
    )
  num_out_error_vals = out_tree.num_leaves - len(out_specs)

  def expand_errors_leading_dim(*xs):
    outs = core.eval_jaxpr(checked_jaxpr, checked_jaxpr.consts, *xs)
    errs, outs = split_list(outs, [num_out_error_vals])
    errs = [lax.expand_dims(e, [0]) for e in errs]
    return *errs, *outs

  with core.extend_axis_env_nd(mesh.shape.items()), config._check_vma(check_vma):
    checked_jaxpr, _ = pe.trace_to_jaxpr(
        expand_errors_leading_dim,
        ft.flatten((tuple(checked_jaxpr.in_avals), {})),
        debug_info=checked_jaxpr.debug_info)

  # 更新 shard_map 参数以考虑额外的错误值。
  # 输出错误使用完全分片的分片方式。
  new_out_specs = (*([P(mesh.axis_names)] * num_out_error_vals), *out_specs)
  new_params = dict(
      jaxpr=checked_jaxpr,
      in_specs=new_in_specs,
      out_specs=new_out_specs,
      **kwargs,
  )
  new_params = jshmap.shard_map_p.get_bind_params(new_params)

  err_and_out = jshmap.shard_map_p.bind(
    *new_vals_in, **new_params)
  return tree_unflatten(out_tree, err_and_out)
error_checks[jshmap.shard_map_p] = shard_map_error_check

def custom_jvp_call_rule(in_err: Error,
                         enabled_errors: set, *in_vals, num_consts,
                         jvp_jaxpr_fun: lu.WrappedFun,
                         call_jaxpr: core.Jaxpr, **params):
  # 需要记住的类型是：
  #   jvp : (a -> b) -> (a, T a) -> (b, T b)
  #   checkify : (a -> b) -> a -> Err b
  #   jvp-of-checkify : (a -> b) -> (a, T a) -> (Err b, T (Err b))
  # 因为 Err 是 pytree，必然有 T (Err b) = Err' (T b)，
  # 其中 Err' 的其余分量都是平凡的（float0 数据类型）。
  # 从语义上说，我们不给 JVP 规则添加检查。要检查
  # JVP 规则的结果，必须改用 checkify-of-jvp。因此本实现
  # 只是把输入的错误与错误码（以及平凡的切向量）转发到输出。
  err_vals, err_tree = jtu.tree_flatten(in_err)
  dbg = call_jaxpr.debug_info
  if dbg.arg_names is not None:
    dbg = dbg._replace(arg_names=("",) * err_tree.num_leaves + dbg.arg_names)
  partial_checkify = lu.wrap_init(
      functools.partial(checkify_jaxpr_flat, call_jaxpr,
                        call_jaxpr.consts, enabled_errors, err_tree),
      debug_info=dbg)
  partial_checkify, f_metadata = _flatten_and_get_error_metadata_thunk(
      partial_checkify)
  jvp = lift_jvp(err_tree.num_leaves, num_consts, jvp_jaxpr_fun)
  jvp, jvp_out_tree = flatten_fun_output(jvp)
  all_outs = custom_derivatives.custom_jvp_call_p.bind(
      *err_vals, *in_vals, subfuns=(partial_checkify, jvp), **params)
  fst, out_metadata = lu.merge_linear_aux(f_metadata, jvp_out_tree)
  if fst:
    err_and_out_tree, _ = out_metadata
    out_err, out_vals = tree_unflatten(err_and_out_tree, all_outs)
  else:
    err_vals, out_vals = split_list(all_outs, [len(err_vals)])
    # 把输入的错误转发到输出
    out_err = jtu.tree_unflatten(err_tree, err_vals)
  return out_err, out_vals
error_checks[custom_derivatives.custom_jvp_call_p] = custom_jvp_call_rule

# 与 custom_derivatives.lift_jvp 相比，我们额外处理了 checkify
# 加入的输入与输出（只是转发错误数据的原始值与
# 切向量分量）。jvp_jaxpr_fun 中的 jaxpr 并不期望这些。
# TODO(mattjj): 能否简化这一实现，或与 custom_derivatives.lift_jvp 去重？
# 再增加一层 lu.transformation 当时很难处理，虽然也许可行。
def lift_jvp(num_errs: int, num_consts: int,
             jvp_jaxpr_fun: lu.WrappedFun) -> lu.WrappedFun:
  def jvp(*xs):
    n, ragged = divmod(len(xs), 2)
    assert not ragged
    primals, tangents = xs[num_consts+num_errs:n], xs[n+num_consts+num_errs:]
    zeros = [type(t) is SymbolicZero for t in tangents]
    jvp_jaxpr, jvp_consts, out_zeros = jvp_jaxpr_fun.call_wrapped(*zeros)
    nonzero_tangents = [t for t in tangents if type(t) is not SymbolicZero]
    out = core.eval_jaxpr(jvp_jaxpr, jvp_consts, *primals, *nonzero_tangents)
    out_primals, nz_out_tangents = split_list(out, [len(out_zeros)])
    nz_out_tangents_ = iter(nz_out_tangents)
    out_tangents = [SymbolicZero(core.typeof(p).to_tangent_aval())
                    if z else next(nz_out_tangents_)
                    for p, z in zip(out_primals, out_zeros)]
    assert next(nz_out_tangents_, None) is None
    primal_errs = xs[num_consts:num_consts+num_errs]
    tangent_errs = xs[n+num_consts:n+num_consts+num_errs]
    return [*primal_errs, *out_primals, *tangent_errs, *out_tangents]
  return lu.wrap_init(jvp, debug_info=jvp_jaxpr_fun.debug_info)

def custom_vjp_call_rule(in_err, enabled_errors, *in_vals,
                         call_jaxpr: core.Jaxpr,
                         fwd_jaxpr_thunk, num_consts,
                         bwd: lu.WrappedFun, out_trees,
                         symbolic_zeros: bool):
  err_vals, err_tree = jtu.tree_flatten(in_err)
  num_errs = err_tree.num_leaves
  checkified_fun = lu.wrap_init(
      functools.partial(checkify_jaxpr_flat, call_jaxpr,
                        call_jaxpr.consts, enabled_errors, err_tree),
      debug_info=call_jaxpr.debug_info)
  checkified_fun, fun_metadata = _flatten_and_get_error_metadata_thunk(
      checkified_fun)

  def checkified_fwd(*args):
    # TODO(lenamartens, sharadmv): 这里为什么不 checkify 呢？
    xs, zeros = args[::2], args[1::2]
    xs, zeros = xs[num_errs:], zeros[num_errs:]
    fwd_jaxpr, fwd_consts = fwd_jaxpr_thunk.call_wrapped(*zeros)
    xs_without_consts = xs[num_consts:]
    return core.eval_jaxpr(fwd_jaxpr, fwd_consts, *xs_without_consts)

  # TODO(necula): 前向的 result_paths 与 fun_jaxpr 并不完全相同
  checkified_fwd_wrapped = lu.wrap_init(checkified_fwd,
                                        debug_info=fwd_jaxpr_thunk.debug_info)
  def bwd_with_errs(*args):
    cts, logs = bwd.call_wrapped(*args)  # 扁平化的 bwd 返回 (cts, logs) 对
    return (*(None,) * num_errs, *cts), logs
  bwd_ = lu.wrap_init(bwd_with_errs, debug_info=bwd.debug_info)
  checkified_fwd_wrapped, fwd_out_tree = flatten_fun_output(checkified_fwd_wrapped)
  all_outs = custom_derivatives.custom_vjp_call_p.bind(
      *err_vals, *in_vals, out_trees=out_trees, symbolic_zeros=symbolic_zeros,
      subfuns=(checkified_fun, checkified_fwd_wrapped, bwd_))
  fst, out_metadata = lu.merge_linear_aux(fun_metadata, fwd_out_tree)
  if fst:
    err_and_out_tree, _ = out_metadata
    out_err, out_vals = tree_unflatten(err_and_out_tree, all_outs)
  else:
    out_err, out_vals = in_err, all_outs
  return out_err, out_vals
error_checks[custom_derivatives.custom_vjp_call_p] = custom_vjp_call_rule


def check_discharge_rule(error, enabled_errors, *args, err_tree, debug):
  del debug
  new_error = tree_unflatten(err_tree, args)
  # 把 new_error 拆分为两部分：若它包含在 enabled_errors 中
  # （=被释放的错误），则要函数化的错误；若不包含
  # （=被重新充入的错误），则要去函数化的错误。
  discharged_error = error
  recharged_error = init_error
  for error_effect in new_error._pred.keys():
    pred = new_error._pred[error_effect]
    code = new_error._code[error_effect]
    payload = new_error._payload[error_effect]
    if error_effect.error_type in enabled_errors:
      discharged_error = update_error(discharged_error, pred, code, {}, payload,
                                      error_effect)
    else:
      recharged_error = update_error(recharged_error, pred, code, {}, payload,
                                     error_effect)

  discharged_error = discharged_error._replace(
      _metadata={**new_error._metadata, **discharged_error._metadata})
  recharged_error = recharged_error._replace(_metadata=new_error._metadata)
  # TODO(lenamartens): 我们其实需要重新充入，但这会是一个
  # 破坏性的 API 变更，所以留待后续处理。
  # check_error(recharged_error)
  return discharged_error, []
error_checks[check_p] = check_discharge_rule


## checkify 公开 API

user_checks = frozenset({FailedCheckError})
nan_checks = frozenset({NaNError})
index_checks = frozenset({OOBError})
div_checks = frozenset({DivisionByZeroError})
float_checks = nan_checks | div_checks
automatic_checks = float_checks | index_checks
all_checks = automatic_checks | user_checks


def checkify(f: Callable[..., Out],
             errors: frozenset[ErrorCategory] = user_checks
             ) -> Callable[..., tuple[Error, Out]]:
  """把 `fun` 中的 `check` 调用函数化，并可选地添加运行时错误检查。

  运行时错误要么是用户添加的 :func:`~check` 断言，要么是
  自动添加的检查（如 NaN 检查），取决于 ``errors`` 参数。

  返回的函数会在原函数的输出之外再返回一个 Error 对象 `err`。
  ``err.get()`` 要么返回 ``None``（未发生错误），要么返回包含错误
  消息的字符串。该错误消息对应第一个发生的错误。若发生错误，
  ``err.throw()`` 会带着错误消息抛出 ValueError。

  默认只启用用户添加的 :func:`~check` 断言。你可以通过
  ``errors`` 参数启用自动检查。

  可启用的自动检查集合，以及它们何时会产生错误：
    - ``user_checks``: 一个 :func:`~check` 求值为 False。
    - ``nan_checks``: 一个浮点运算产生了 NaN 值作为输出。
    - ``div_checks``: 一次除零。
    - ``index_checks``: 一个索引越界。

  传入一个错误 `Set` 可以同时启用多个类别（例如
  ``errors=nan_checks``）。多个集合也可以重新组合（例如
  ``errors=float_checks|user_checks``）

  Args:
    fun: 可以包含用户检查的可调用对象（见 :func:`~check`）。
    errors: 一组 ErrorCategory 值，定义要启用的检查集合。
      默认只启用显式的 ``checks``（``user_checks``）。你也可以
      例如传入 ``float_checks`` 集合来启用 NAN 与 DIV 错误，或者
      通过集合运算组合多个集合
      （``float_checks | user_checks``）
  Returns:
    一个函数，它接受与 ``fun`` 相同的参数，并返回一个二元组：
    第一个元素是 ``Error`` 值，表示第一个失败的 :func:`~check`；
    第二个元素是 ``fun`` 的原始输出。

  例如：

    >>> import jax
    >>> import jax.numpy as jnp
    >>> from jax.experimental import checkify
    >>>
    >>> @jax.jit
    ... def f(x):
    ...   y = jnp.sin(x)
    ...   return x+y
    >>> err, out = checkify.checkify(f, errors=checkify.float_checks)(jnp.inf)
    >>> err.throw()  # doctest: +IGNORE_EXCEPTION_DETAIL
    Traceback (most recent call last):
      ...
    jax._src.checkify.JaxRuntimeError: nan generated by primitive: sin
  """
  @traceback_util.api_boundary
  def checked_fun(*args, **kwargs):
    # 闭包捕获所有参数，使它们不会被转换为抽象值。
    in_avals = ft.flatten(((), {}))
    closed_f = lambda: f(*args, **kwargs)
    # 暂存：
    debug_info = api_util.debug_info("checkify", f, args, kwargs).with_unknown_names()
    jaxpr_, out_avals = pe.trace_to_jaxpr(closed_f, in_avals, debug_info)
    jaxpr, consts = pe.separate_consts(jaxpr_)
    # checkify：
    error, out_flat = checkify_jaxpr(jaxpr, errors, init_error, *consts)
    return error, out_avals.update(out_flat).unflatten()
  return checked_fun

def check(pred: Bool, msg: str,
          *fmt_args,
          debug: bool = False,
          **fmt_kwargs,
          ) -> None:
  """检查一个谓词，若谓词为 False 则添加带 msg 的错误。

  这是一个有副作用的操作，不能被暂存（jitted/scanned/...）。
  在对带检查的函数做暂存之前，先 :func:`~checkify` 它！

  Args:
    pred: 若为 False，则添加一个 FailedCheckError 错误。
    msg: 添加错误时的错误消息。可以是格式字符串。
    debug: 是否开启调试模式。若为 True，check 会在执行时被移除。
      若为 False，则必须用 checkify.checkify 把该检查函数化。
    fmt_args, fmt_kwargs: `msg` 的位置与关键字格式化参数，例如：
      ``check(.., "check failed on values {} and {named_arg}", x, named_arg=y)``
      注意这些参数可以是追踪值，从而允许你向错误消息中加入
      运行时的值。
      注意追踪这些运行时数组会增加内存占用，
      即使没有发生错误也是如此。

  例如：

    >>> import jax
    >>> import jax.numpy as jnp
    >>> from jax.experimental import checkify
    >>> def f(x):
    ...   checkify.check(x>0, "{x} needs to be positive!", x=x)
    ...   return 1/x
    >>> checked_f = checkify.checkify(f)
    >>> err, out = jax.jit(checked_f)(-3.)
    >>> err.throw()  # doctest: +IGNORE_EXCEPTION_DETAIL
    Traceback (most recent call last):
      ...
    jax._src.checkify.JaxRuntimeError: -3. needs to be positive!

  """
  _check(pred, msg, debug, *fmt_args, **fmt_kwargs)

def _check(pred, msg, debug, *fmt_args, **fmt_kwargs):
  if not is_scalar_pred(pred):
    prim_name = 'debug_check' if debug else 'check'
    raise TypeError(f'{prim_name} takes a scalar pred as argument, got {pred}')
  for arg in jtu.tree_leaves((fmt_args, fmt_kwargs)):
    if not isinstance(arg, (Array, np.ndarray)):
      raise TypeError('Formatting arguments to checkify.check need to be '
                      'PyTrees of arrays, but got '
                      f'{arg!r} of type {type(arg)}.')
  new_error = FailedCheckError(get_traceback(), msg, *fmt_args, **fmt_kwargs)
  error = assert_func(init_error, jnp.logical_not(pred), new_error)
  _check_error(error, debug=debug)

def _check_error(error, *, debug=False):
  if any(map(np.shape, error._pred.values())):
    error = _reduce_any_error(error)
  err_args, tree_def = tree_flatten(error)

  return check_p.bind(*err_args, err_tree=tree_def, debug=debug)


def is_scalar_pred(pred) -> bool:
  return (isinstance(pred, bool) or
          isinstance(pred, Array) and pred.shape == () and
          pred.dtype == np.dtype('bool'))


def debug_check(pred: Bool, msg: str, *fmt_args, **fmt_kwargs) -> None:
  """在 checkify 下运行时检查一个谓词，否则是空操作。

  `debug_check` 只有在被 :func:`~checkify` 变换时才会运行，
  否则该检查会被丢弃。

  Args:
    pred: 若为 False，则添加一个 FailedCheckError 错误。
    msg: 添加错误时的错误消息。
    fmt_args, fmt_kwargs: `msg` 的位置与关键字格式化参数，例如：
      ``debug_check(.., "check failed on values {} and {named}", x, named=y)``
      注意这些参数可以是追踪值，从而允许你向错误消息中加入
      运行时的值。
      注意追踪这些运行时数组会增加内存占用，
      即使没有发生错误也是如此。

  例如：

    >>> import jax
    >>> import jax.numpy as jnp
    >>> from jax.experimental import checkify
    >>> def f(x):
    ...   checkify.debug_check(x!=0, "cannot be zero!")
    ...   return x
    >>> _ = f(0)  # running without checkify means no debug_check is run.
    >>> checked_f = checkify.checkify(f)
    >>> err, out = jax.jit(checked_f)(0)  # running with checkify runs debug_check.
    >>> err.throw()  # doctest: +IGNORE_EXCEPTION_DETAIL
    Traceback (most recent call last):
      ...
    jax._src.checkify.JaxRuntimeError: cannot be zero!

  """
  _check(pred, msg, True, *fmt_args, **fmt_kwargs)


def check_error(error: Error) -> None:
  """若 ``error`` 表示一次失败，则抛出异常。由 :func:`~checkify` 函数化。

  该函数的语义等价于：

  >>> def check_error(err: Error) -> None:
  ...   err.throw()  # can raise ValueError

  但与那个实现不同，``check_error`` 可以用
  :func:`~checkify` 变换来函数化。

  该函数与 :func:`~check` 类似，但签名不同：:func:`~check` 以
  布尔谓词和新的错误消息字符串为参数，而该函数以 ``Error``
  值为参数。:func:`~check` 与该函数在失败时都会抛出 Python
  异常（一种副作用），因此无法被 :func:`~jax.jit`、:func:`~jax.pmap`、
  :func:`~jax.lax.scan` 等暂存出去。二者也都可以
  用 :func:`~checkify` 函数化。

  但与 :func:`~check` 不同，该函数像是 :func:`~checkify` 的直接逆：
  :func:`~checkify` 接受一个可能抛出 Python
  异常的函数，产生一个没有该效果、但以 ``Error`` 值为输出的
  新函数；而这个 ``check_error`` 函数可以接受 ``Error`` 值作为
  输入，并产生抛出异常的副作用。也就是说，:func:`~checkify` 是
  从可函数化的异常效果走向错误值，而这个 ``check_error`` 则是从错误
  值走向可函数化的异常效果。

  当你想把由 ``Error`` 值（通过 :func:`~checkify` 函数化
  ``checks`` 得到）表示的检查重新变回 Python 异常时，
  ``check_error`` 很有用。

  Args:
    error: 要检查的 Error。

  例如，你可能想用 checkify 函数化程序的一部分，把函数化后的
  代码通过 :func:`~jax.jit` 暂存出去，然后在 :func:`~jax.jit`
  之外重新注入你的错误值：

  >>> import jax
  >>> from jax.experimental import checkify
  >>> def f(x):
  ...   checkify.check(x>0, "must be positive!")
  ...   return x
  >>> def with_inner_jit(x):
  ...   checked_f = checkify.checkify(f)
  ...   # a checkified function can be jitted
  ...   error, out = jax.jit(checked_f)(x)
  ...   checkify.check_error(error)
  ...   return out
  >>> _ = with_inner_jit(1)  # no failed check
  >>> with_inner_jit(-1)  # doctest: +IGNORE_EXCEPTION_DETAIL
  Traceback (most recent call last):
    ...
  jax._src.JaxRuntimeError: must be positive!
  >>> # can re-checkify
  >>> error, _ = checkify.checkify(with_inner_jit)(-1)
  """
  if not isinstance(error, Error):
    raise TypeError('check_error takes an Error as argument, '
                     f'got type {type(error)} instead.')
  _check_error(error, debug=False)
